let car = "subaru"
console.log(car == 'subaru')
console.log(car != 'subaru')
console.log(car.length != 'subaru'.length)
console.log(car.length == 'subaru'.length)
console.log(car.charAt[0] == 'subaru')
console.log(car.charAt[0] == 'subaru'.charAt[0])
console.log(car.slice(1.4) != 'subaru'.slice(1.4))
console.log(car.slice(1.4) == 'subaru'.slice(1.4))
console.log(car.replace('s','t') == 'subaru')
console.log(car.replace('s','t') != 'subaru')
